# Generated by Django 6.0.4 on 2026-04-24 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_productsource_orderitem_status_kitchenlog_and_more'),
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='session',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='orders.tablesession'),
            preserve_default=False,
        ),
    ]
