# Generated by Django 6.0.4 on 2026-05-01 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_kitchenlog_active_session_order_active_session_and_more'),
        ('payments', '0003_payment_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='active_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.activetablesession'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.tablesession'),
        ),
    ]
