# Generated by Django 6.0.4 on 2026-04-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('waiter', 'Waiter'), ('kitchen', 'Kitchen Staff'), ('cashier', 'Cashier'), ('manager', 'Manager')], default='waiter', max_length=20),
        ),
    ]
