# Generated by Django 6.0.4 on 2026-05-03 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('waiter', 'Waiter'), ('kitchen', 'Kitchen Staff'), ('bar', 'Bar Staff'), ('cafe', 'Cafe Staff'), ('pastry', 'Pastry Staff'), ('cashier', 'Cashier'), ('manager', 'Manager')], default='waiter', max_length=20),
        ),
    ]
