# Generated by Django 6.0.4 on 2026-04-24 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderitem_product_source_alter_orderitem_quantity_and_more'),
        ('products', '0004_remove_productsource_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemstatus',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productsource'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.productsource'),
        ),
        migrations.DeleteModel(
            name='ProductSource',
        ),
    ]
