# Generated by Django 6.0.4 on 2026-04-30 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_orderitemstatus_station_orderitem_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Pending Approval'), ('pending', 'Pending'), ('needs_confirmation', 'Needs Confirmation'), ('confirmed', 'Confirmed'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('served', 'Served'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
