# Generated by Django 6.0.4 on 2026-04-30 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_status'),
        ('users', '0003_alter_user_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TableAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.table')),
            ],
            options={
                'ordering': ['table__number'],
            },
        ),
        migrations.CreateModel(
            name='ActiveTableSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('is_client_identified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.client')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.table')),
                ('waiter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_tables', to=settings.AUTH_USER_MODEL)),
                ('current_assignment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.tableassignment')),
            ],
        ),
        migrations.CreateModel(
            name='WorkShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_type', models.CharField(choices=[('morning', 'Morning Shift (8:00 - 14:00)'), ('afternoon', 'Afternoon Shift (14:00 - 20:00)'), ('evening', 'Evening Shift (20:00 - 2:00)'), ('custom', 'Custom Shift')], default='morning', max_length=20)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('shift_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shifts', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-shift_date', 'employee'],
            },
        ),
        migrations.AddField(
            model_name='tableassignment',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_assignments', to='orders.workshift'),
        ),
        migrations.AlterUniqueTogether(
            name='tableassignment',
            unique_together={('shift', 'table')},
        ),
    ]
