# Generated by Django 6.0.4 on 2026-05-01 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_tableassignment_activetablesession_workshift_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchenlog',
            name='active_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.activetablesession'),
        ),
        migrations.AddField(
            model_name='order',
            name='active_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='orders.activetablesession'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='active_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.activetablesession'),
        ),
        migrations.AlterField(
            model_name='kitchenlog',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.tablesession'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Pending Approval'), ('pending', 'Pending'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('served', 'Served')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.tablesession'),
        ),
    ]
