# Generated by Django 6.0.4 on 2026-05-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_kitchenlog_active_session_order_active_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activetablesession',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activetablesession',
            name='last_activity_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='activetablesession',
            name='payment_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
