# Generated by Django 6.0.4 on 2026-04-24 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productsource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsource',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='productsource',
            name='description',
        ),
        migrations.RemoveField(
            model_name='productsource',
            name='location',
        ),
        migrations.AddField(
            model_name='productsource',
            name='station_type',
            field=models.CharField(choices=[('kitchen', 'Kitchen'), ('bar', 'Bar'), ('cafe', 'Cafe'), ('pastry', 'Pastry')], default='kitchen', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='product_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.productsource'),
        ),
    ]
