# Generated by Django 6.0.4 on 2026-04-24 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_productsource_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsource',
            name='station_type',
            field=models.CharField(choices=[('kitchen', 'Kitchen'), ('bar', 'Bar'), ('cafe', 'Cafe'), ('pastry', 'Pastry')], default='kitchen', max_length=20),
        ),
    ]
